### ISSUE TITLE
documentation on npm is showing dots instead of colons for directive arg

### ISSUE THREAD

**Issue by undefinederror** [David-Desmaisons/Vue.resize#2]
README version published on npm uses wrong separators between [directive] and [arg] (dots instead of colons)

![image](https://user-images.githubusercontent.com/8209966/28172778-d9c06c34-67ec-11e7-8102-63ed1829e5e2.png)

Please update it because it's pretty misleading. Took me while to figure out why debounce/throttle were completely ignored.

**Comment by David-Desmaisons** [comment]
@undefinederror , This will be corrected when next version will be published

**Comment by David-Desmaisons** [comment]
Corrected in version 1.0.1
