### ISSUE TITLE
Why is vue-resize-directive not firing?

### ISSUE THREAD

**Issue by yuncode** [David-Desmaisons/Vue.resize#3]
three  steps
1. `npm install vue-resize-directive --save`
2.
```
// ES6
import resize from 'vue-resize-directive'
//...
export default {
    directives: {
        resize,
    }
//...
```
3.`<div v-resize="onResize">`

finnally   div  no effect

**Comment by David-Desmaisons** [comment]
1) What is your implementation of onResize method?
2) What is the scenario you are testing and give "no effect"?

**Comment by yuncode** [comment]
@David-Desmaisons  thank you very much ，I wrongly thought this Library was used to resize Dom 。 。
sorry 。 and  i suggest  your project name shoud be  vue-resize-listen
