### ISSUE TITLE
[wish] add an "initial" modifier to the directive to fire always at mount

### ISSUE THREAD

**Issue by nahuel** [David-Desmaisons/Vue.resize#6]
It will be very useful to make the resize event fire at least one time, right after the element is mounted on the DOM. Maybe adding a modifier like `<div v-resize:initial="onResize">`. This is already implemented on this library: https://github.com/FranckFreiburger/vue-resize-sensor#initial-boolean

**Comment by David-Desmaisons** [comment]
Hello @nahuel , you can use the vue mounted method for this purpose. I do not see this feature as generic enought .

**Comment by David-Desmaisons** [comment]
I end up providing this feature in version 1.1.0
