### ISSUE TITLE
child component used v-resize, when parent used in v-show, it not work

### ISSUE THREAD

**Issue by zsedcbm** [David-Desmaisons/Vue.resize#7]
child component used v-resize

when parent used v-show, then child resize event is not work

when parent used v-if, then child resize event is work

![4](https://user-images.githubusercontent.com/5986396/40224209-0b73028c-5ab8-11e8-81e4-a2d83c743f0d.gif)

[https://codepen.io/zsedcbm/pen/erQomg](https://codepen.io/zsedcbm/pen/erQomg)

**Comment by David-Desmaisons** [comment]
I see nothing wrong. Please define the expected behaviour and why it is not ok in case of v-show.

**Comment by zsedcbm** [comment]
I feedback this problem to **css-element-queries** , which can also occur when use **css-element-queries** alone
[https://github.com/marcj/css-element-queries/issues/228](https://github.com/marcj/css-element-queries/issues/228)

**Comment by zsedcbm** [comment]
when i use v-show, child component's val is not change, is always 10
when i use v-if, child components's  v-resize worked, val is changed

**Comment by David-Desmaisons** [comment]
Corrected in version 1.1.0.
