### ISSUE TITLE
Does not work on singleton tags

### ISSUE THREAD

**Issue by northamerican** [David-Desmaisons/Vue.resize#9]
The directive fails with `<img>` elements and other singletons. The `v-resize` callback is not triggered. Probably because the `resize-sensor` is placed inside the target element and singletons cannot have elements inside them.

**Comment by northamerican** [comment]
Additionally, if support for img tags were implemented, it would be neat if it also took into account the internal size of an image with `object-fit: cover` set.

**Comment by David-Desmaisons** [comment]
@northamerican It is inherent to the way resize-sensor works as you pointed it out. So this will be a permante restriction this direcyive does not apply in such cases
